# https://docs.travis-ci.com/user/getting-started/
# https://docs.travis-ci.com/user/languages/scala/#sbt-Dependency-Management
language: scala
scala:
- 2.12.2
jdk:
- openjdk8
before_install:
- sudo apt-get install graphviz-dev
script:
#- sbt ++$TRAVIS_SCALA_VERSION test:testOnly *TSqlTests
- sbt ++$TRAVIS_SCALA_VERSION test
#- sbt clean coverage test coverageReport &&
#  sbt coverageAggregate
#after_success:
#- sbt coveralls